export const projects = [
  {
    title: 'Personal Portfolio',
    description: "Using React, Node.js, Express & MongoDB you'll learn how to build a Full Stack MERN Application - from start to finish. The App is called Memories and it is a simple social media app that allows users to post interesting events that happened in their lives.",
      image: '/images/1.png',
      tags: ['ReactJS', 'NextJS', 'CSS', 'HTML', 'Styles'],
    source: 'https://github.com/HetMamtora/Personal-Portfolio',
    visit: 'https://google.com',
    id: 0,
  },
  {
    title: 'Business Landing Page',
    description:"While building it you're going to learn many advanced React & JavaScript topics, as well as how to use Stripe for card transactions. On top of that, at the end of the video, you will have this unique and complex webshop app that you will be able to add to your portfolio. And trust me, e-commerce applications are impressive.",
    image: '/images/2.png',
    tags: ['ReactJS', 'TailwindCSS', 'HTML', 'UI/UX', 'VITE Environment'],
    source: 'https://github.com/HetMamtora/HooBank-App-ReactJS-TailwindCSS',
    visit: 'https://hoobank-modernapp-tailwindcss-reactjs.netlify.app/',
    id: 1,
  },
  {
    title: 'Modern Restaurant Landing Page',
    description: "This is a code repository for the corresponding YouTube video. In this tutorial, we're going to build and deploy a React Video Chat Application using WebRTC.",
      image: '/images/3.png',
      tags: ['ReactJS', 'CSS', 'CSS BEM Mode', 'HTML', 'UI/UX'],
    source: 'https://github.com/HetMamtora/ModernRestaurent-UI-UX',
    visit: 'https://modern-restaurant-ui-ux.netlify.app/',
    id: 2,
  },
  {
    title: 'What GPT3 UI/UX Page',
    description: "This is a code repository for the corresponding video tutorial. In this video, we will create a full Realtime Chat Application",
    image: '/images/4.png',
    tags: ['ReactJS', 'CSS', 'File Structure', 'HTML', 'UI/UX'],
    source: 'https://github.com/HetMamtora/WhatGPT3-ReactJS',
    visit: 'https://whatgpt-3-openai.netlify.app/',
    id: 3,
  },
  {
    title: 'ECommerce - MERN Stack',
    description: "This is a code repository for the corresponding video tutorial. In this video, we will create a full Realtime Chat Application",
    image: '/images/5.png',
    tags: ['MongoDB', 'ExpressJS', ' ReactJS', ' NodeJS'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 4,
  },
];

export const TimeLineData = [
  { year: 2016, text: 'Passed my 10th SSC Board with 64%.', },
  { year: 2017, text: 'Took admit in Tolani Foundation Gandhidham Polytechnic for diploma in Computer Engineering.', },
  { year: 2020, text: 'Passed my Diploma with 8.94/10 CGPA and got admitted into Nirma University', },
  { year: 2023, text: "Graduated in May'23 from Nirma Universiry, majored in Computer Science Engineering with 7.03/10 CGPA.", },
  { year: 2023, text: 'Since June developing projects to up bring and master my skills with web development.', },
];