export const projects = [
  {
    title:'RealTime Chat App [Under Development]',
    description:"Under development phase. Currently designing the backend part with both user and admin authentications. Targeting to get and engage real time users after completion. More updation in tech stack is under progress.",
    image:'/images/chat_app.png',
    tags:['MongoDB', 'ExpressJS', 'ReactJS', 'NextJS', 'NodeJS'],
    source:'https://github.com/HetMamtora/project',
    visit:'https://github.com/HetMamtora/project',
    id:0,
  },
  {
    title: 'Personal Portfolio',
    description: "Using ReactJS, NextJS, Styles and CSS I have built an excellent looking personal portfolio web page displaying svg animation and project cards. This web page is responsive over different devices  and also demonstrated carousel for mobile devices. This project helped me to gain deeper insights over NextJS.",
    image: '/images/portfolio.png',
    tags: ['ReactJS', 'NextJS', 'CSS', 'HTML', 'Styles'],
    source: 'https://github.com/HetMamtora/Personal-Portfolio',
    visit: 'https://het-mamtora-portfolio.netlify.app/',
    id: 1,
  },
  {
    title:'Show Booking - MERN',
    description:"NodeJS, ExpressJS , MongoDB is used to retrieve details from front-end and book the ticket to save at Back-End. Shows the last booking from the database on front-end part which is designed whole using ReactJS.",
    image:'/images/show_booking.png',
    tags:['MongoDB Atlas', 'ExpressJS', 'ReactJS', 'NodeJS'],
    source:'https://github.com/HetMamtora/MERN-ShowBooking',
    visit:'https://github.com/HetMamtora/MERN-ShowBooking',
    id:2,
  },
  {
    title:'MERN-Ecommerce',
    description:"Node, Express and MongoDB Atlas used all together for backend and postman is used for API testing. Using ReactJS the whole frontend part is designed to make the app more visual appealing.",
    image:'/images/ecommerce.png',
    tags:['MongoDB,', 'Express,', 'React,', 'Node,', 'Cloudinary,', 'Postman'],
    source:'https://github.com/HetMamtora/MERN-ECommerce',
    visit:'https://github.com/HetMamtora/MERN-ECommerce',
    id:3,
  },
  {
    title:'MERN Login/Registration',
    description:"Demonstrated a basic MERN app with Login and Registration functionality with database MongoDB. Also the code is useful to integrate over other projects which need functionality of login and registration.",
    image:'/images/login-reg.png',
    tags:['MongoDB', 'ExpressJS', 'ReactJS', 'NodeJS'],
    source:'https://github.com/HetMamtora/MERN-LoginRegistration',
    visit:'https://github.com/HetMamtora/MERN-LoginRegistration',
    id:4,
  },
  {
    title:'YouTube Clone',
    description:"Developed a YouTube clone utilizing ReactJS, TailwindCSS, and Redux Toolkit for state management. Used Google Cloud API to enable seamless video streaming and enhance user experience with V3 youtube API.",
    image:'/images/yt_clone.png',
    tags:['ReactJS', 'TailwindCSS', 'Redux', 'Google Cloud API'],
    source:'https://github.com/HetMamtora/YouTube-clone-ReactJS',
    visit:'https://youtube-clone-hm.netlify.app/',
    id:5,
  },
  {
    title:'ReactJS Projects [links in repo] ',
    description:"Demonstrated frontend development skills using ReactJS, HTML, CSS, and JavaScript over multiple projects all in one repo.",
    image:'/images/react_projects.png',
    tags:['ReactJS', 'HTML', 'CSS', 'JavaScript '],
    source:'https://github.com/HetMamtora/ReactJS-Projects',
    visit:'https://github.com/HetMamtora/ReactJS-Projects',
    id:6,
  },
  {
    title:'JavaScript Projects [links in repo] ',
    description:"Pure JavaScript project shows how flow of code works with dedicated functionality provided within the projects.",
    image:'/images/JS_projects.png',
    tags:['JavaScript','HTML', 'CSS'],
    source:'https://github.com/HetMamtora/JavaScript-Intermediate',
    visit:'https://github.com/HetMamtora/JavaScript-Intermediate',
    id:7,
  },
  
  {
    title: 'Business Landing Page',
    description:"Using ReactJS & TailwindCSS, built a modern business landing page of a bank as an example. TailwindCSS is used for high customization. Development environment was paired with VITE + React for the better development of the code. Web page is Responsive over different devices for better usage.",
    image: '/images/2.png',
    tags: ['ReactJS', 'TailwindCSS', 'HTML', 'UI/UX', 'VITE Environment'],
    source: 'https://github.com/HetMamtora/HooBank-App-ReactJS-TailwindCSS',
    visit: 'https://hoobank-modernapp-tailwindcss-reactjs.netlify.app/',
    id: 8,
  },
  {
    title: 'Modern Restaurant Landing Page',
    description: "Using ReactJS, CSS BEM Model, CSS, HTML and a ready Figma Design. I made this beautiful modern restaurant landing page demonstrating the usage of ReactJS and CSS Bem Model with responsiveness over different devices.",
      image: '/images/3.png',
      tags: ['ReactJS', 'CSS', 'CSS BEM Mode', 'HTML', 'UI/UX'],
    source: 'https://github.com/HetMamtora/ModernRestaurent-UI-UX',
    visit: 'https://modern-restaurant-ui-ux.netlify.app/',
    id: 9,
  },
  {
    title: 'What GPT3 UI/UX Page',
    description: "This modern page of WhatGPT-3 is demonstrating the use of ReactJS and CSS with all the file structure of React. This webpage is responsive over different devices with perfectly placed media queries and has been developed using a ready Figma Design.",
    image: '/images/4.png',
    tags: ['ReactJS', 'CSS', 'File Structure', 'HTML', 'UI/UX'],
    source: 'https://github.com/HetMamtora/WhatGPT3-ReactJS',
    visit: 'https://whatgpt-3-openai.netlify.app/',
    id: 10,
  },
  {
    title: 'ECommerce - MERN Stack',
    description: "Enables end-users to browse, search for, and purchase products online. 3rd-Party technologies and tools used, Cloudinary-image storage, Stripe-payment processing, Postman-API testing.",
    image: '/images/5.png',
    tags: ['MongoDB', 'ExpressJS', ' ReactJS', ' NodeJS'],
    source: 'https://github.com/HetMamtora/ECommerce-MERNstack',
    visit: 'https://github.com/HetMamtora/ECommerce-MERNstack',
    id: 11,
  },
];

export const TimeLineData = [
  { year: 2024, text: 'In between I joined some Freelance groups as helping hands to get insights about recent development in IT industries.', },
  { year: 2024, text: 'Started with self paced projects in January  followed by 100 Days of Coding challenge to up skill myself at advance level in Full Stack Development', },
  { year: 2023, text: 'In December, my internship was over after commencement of it for 4 months duration.', },
  { year: 2023, text: 'In September, onboarded Cognizant, Chennai for my Internship in GenC Programmer Analyst', },
  { year: 2023, text: 'June onwards, started developing and up skilling myself with React based projects.', },
  { year: 2023, text: 'Graducted in May from Nirma University scoring 7.03/10 CGPA.', },
  { year: 2020, text: 'Admitted in Nirma University for my Bachelors in Computer Science Engineering.', },
  { year: 2020, text: 'Passed diploma in August scoring rank across district with 8.95/10 CGPA.', },
  { year: 2017, text: 'Admitted in Diploma Computer Engineering at Tolani Foundation Gandhidham Polytechnic.', },
  { year: 2016, text: 'Passed SSC Board of 10th.', },
];
