export const projects = [
  {
    title: 'Personal Portfolio',
    description: "Using ReactJS, NextJS, Styles and CSS I have built an excellent looking personal portfolio web page displaying svg animation and project cards. This web page is responsive over different devices  and also demonstrated carousel for mobile devices. This project helped me to gain deeper insights over NextJS.",
      image: '/images/1.png',
      tags: ['ReactJS', 'NextJS', 'CSS', 'HTML', 'Styles'],
    source: 'https://github.com/HetMamtora/Personal-Portfolio',
    visit: 'https://het-mamtora-portfolio.netlify.app/',
    id: 0,
  },
  {
    title: 'Business Landing Page',
    description:"Using ReactJS & TailwindCSS, built a modern business landing page of a bank as an example. TailwindCSS is used for high customization. Development environment was paired with VITE + React for the better development of the code. Web page is Responsive over different devices for better usage.",
    image: '/images/2.png',
    tags: ['ReactJS', 'TailwindCSS', 'HTML', 'UI/UX', 'VITE Environment'],
    source: 'https://github.com/HetMamtora/HooBank-App-ReactJS-TailwindCSS',
    visit: 'https://hoobank-modernapp-tailwindcss-reactjs.netlify.app/',
    id: 1,
  },
  {
    title: 'Modern Restaurant Landing Page',
    description: "Using ReactJS, CSS BEM Model, CSS, HTML and a ready Figma Design. I made this beautiful modern restaurant landing page demonstrating the usage of ReactJS and CSS Bem Model with responsiveness over different devices.",
      image: '/images/3.png',
      tags: ['ReactJS', 'CSS', 'CSS BEM Mode', 'HTML', 'UI/UX'],
    source: 'https://github.com/HetMamtora/ModernRestaurent-UI-UX',
    visit: 'https://modern-restaurant-ui-ux.netlify.app/',
    id: 2,
  },
  {
    title: 'What GPT3 UI/UX Page',
    description: "This modern page of WhatGPT-3 is demonstrating the use of ReactJS and CSS with all the file structure of React. This webpage is responsive over different devices with perfectly placed media queries and has been developed using a ready Figma Design.",
    image: '/images/4.png',
    tags: ['ReactJS', 'CSS', 'File Structure', 'HTML', 'UI/UX'],
    source: 'https://github.com/HetMamtora/WhatGPT3-ReactJS',
    visit: 'https://whatgpt-3-openai.netlify.app/',
    id: 3,
  },
  {
    title: 'ECommerce - MERN Stack',
    description: "This project is developed using MongoDB, ExpressJS, ReactJS, and NodeJS with RestfulAPIs and Redux Toolkit. Also integrated with CDN for faster image loading and STRIPE API for faster and safer payment gateway. All of the APIs were tested using Postman for better validation. [Posted Only GIT REPO with images]",
    image: '/images/5.png',
    tags: ['MongoDB', 'ExpressJS', ' ReactJS', ' NodeJS'],
    source: 'https://github.com/HetMamtora/ECommerce-MERNstack',
    visit: 'https://github.com/HetMamtora/ECommerce-MERNstack',
    id: 4,
  },
];

export const TimeLineData = [
  { year: 2024, text: 'In between I joined some Freelance groups as helping hands to get insights about recent development in IT industries.', },
  { year: 2024, text: 'Started with self paced projects in January  followed by 100 Days of Coding challenge to up skill myself at advance level in Full Stack Development', },
  { year: 2023, text: 'In December, my internship was over after commencement of it for 4 months duration.', },
  { year: 2023, text: 'In September, onboarded Cognizant, Chennai for my Internship in GenC Programmer Analyst', },
  { year: 2023, text: 'June onwards, started developing and up skilling myself with React based projects.', },
  { year: 2023, text: 'Graducted in May from Nirma University scoring 7.03/10 CGPA.', },
  { year: 2020, text: 'Admitted in Nirma University for my Bachelors in Computer Science Engineering.', },
  { year: 2020, text: 'Passed diploma in August scoring rank across district with 8.95/10 CGPA.', },
  { year: 2017, text: 'Admitted in Diploma Computer Engineering at Tolani Foundation Gandhidham Polytechnic.', },
  { year: 2016, text: 'Passed SSC Board of 10th.', },
];
